apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: segment-backup-job
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/segment-backup-job/segment-backup-job@sha256:343f1c054f2f5001927901485f758ddef7e26cc42bc23d41c420056b074c09db
        name: my-python
        resources: {}
status: {}
