apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: segment-backup-job
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/segment-backup-job/segment-backup-job@sha256:2936f4f6496a50f495ed78b30f94899dbea7c0bb71052bb76928411000a31bb7
        name: my-python
        resources: {}
status: {}
