apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: segment-backup-job
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/segment-backup-job/segment-backup-job@sha256:d57c5369593a0e21bdd704b73f856388be5dc723585bb957fb56b1d4d1e0240d
        name: my-python
        resources: {}
status: {}
