apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: segment-backup-job
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: segment-backup-job
    app.kubernetes.io/part-of: segment-backup-job
  name: segment-backup-jobyydy
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: segment-backup-job
    weight: null
status: {}
