apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: segment-backup-job
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: segment-backup-job
    app.kubernetes.io/part-of: segment-backup-job
  name: segment-backup-job
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: segment-backup-job
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: segment-backup-job
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/segment-backup-job/segment-backup-job@sha256:ba29277de39fff4d9692ad6e39aec006094c413fc8984a048ba7fd08b976caad
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
