apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: segment-backup-job
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: segment-backup-job
    app.kubernetes.io/part-of: segment-backup-job
  name: segment-backup-job
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: segment-backup-job
status:
  loadBalancer: {}
